using System.ComponentModel.DataAnnotations;

namespace EventsApp.Models
{
    public enum EventGenre
    {
        [Display(Name = "Друго")]
        Other = 0,
        [Display(Name = "Рок")]
        Rock = 1,
        [Display(Name = "Поп")]
        Pop = 2,
        [Display(Name = "Хип-хоп")]
        HipHop = 3,
        [Display(Name = "Електронна")]
        Electronic = 4,
        [Display(Name = "Джаз")]
        Jazz = 5,
        [Display(Name = "Класическа")]
        Classical = 6,
        [Display(Name = "Фолк")]
        Folk = 7,
        [Display(Name = "Метъл")]
        Metal = 8,
        [Display(Name = "Театър")]
        Theater = 9,
        [Display(Name = "Стендъп")]
        Standup = 10,
        [Display(Name = "Фестивал")]
        Festival = 11,
        [Display(Name = "Изложба")]
        Exhibition = 12,
        [Display(Name = "Спорт")]
        Sports = 13,
        [Display(Name = "Конференция")]
        Conference = 14,
        [Display(Name = "Работилница")]
        Workshop = 15,
        [Display(Name = "Techno")]
        Techno = 16,
        [Display(Name = "House")]
        House = 17,
        [Display(Name = "Drum and Bass")]
        DrumAndBass = 18,
        [Display(Name = "Trap")]
        Trap = 19,
        [Display(Name = "Rnb")]
        Rnb = 20,
        [Display(Name = "Punk")]
        Punk = 21,
        [Display(Name = "Indie")]
        Indie = 22,
        [Display(Name = "Alternative")]
        Alternative = 23,
        [Display(Name = "Blues")]
        Blues = 24,
        [Display(Name = "Reggae")]
        Reggae = 25,
        [Display(Name = "Latino")]
        Latino = 26,
        [Display(Name = "Chalga")]
        Chalga = 27,
        [Display(Name = "Disco")]
        Disco = 28,
        [Display(Name = "Live Music")]
        LiveMusic = 29,
        [Display(Name = "Opera")]
        Opera = 30,
        [Display(Name = "Ballet")]
        Ballet = 31,
        [Display(Name = "Cinema")]
        Cinema = 32,
        [Display(Name = "Comedy")]
        Comedy = 33,
        [Display(Name = "Kids")]
        Kids = 34,
        [Display(Name = "Food and Drinks")]
        FoodAndDrinks = 35,
        [Display(Name = "Art")]
        Art = 36,
        [Display(Name = "Networking")]
        Networking = 37,
        [Display(Name = "Charity")]
        Charity = 38,
        [Display(Name = "Outdoor")]
        Outdoor = 39,
        [Display(Name = "Nightlife")]
        Nightlife = 40,
        [Display(Name = "Gaming")]
        Gaming = 41,
    }
}
